import type { OpportunityRow } from './types'

// Dados fictícios só para exercitar a UI (CLAUDE.md: nunca dado real de cliente).
export const sampleOpportunities: OpportunityRow[] = [
  {
    id: 'opp-1',
    companyName: 'Aurora Sistemas Ltda',
    isCustomer: true,
    opportunityScore: 0.92,
    financialPotential: 48000,
    type: 'cross-sell',
    product: 'VDC365',
    service: null,
    priority: 'alta',
    sources: [{ type: 'salesforce', confidence: 1 }, { type: 'website', confidence: 0.8 }],
    status: 'qualified',
    evidence: ['veeam_vbr', 'm365'],
    justification: 'Cliente tem Veeam VBR e M365, mas não tem VDC365.',
    confidenceScore: 0.9,
    currentProducts: ['Veeam VBR', 'Microsoft 365'],
    recommendedProducts: ['VDC365'],
    recommendedServices: [],
  },
  {
    id: 'opp-2',
    companyName: 'Bytemark Tecnologia',
    isCustomer: false,
    opportunityScore: 0.67,
    financialPotential: 15000,
    type: 'service',
    product: null,
    service: 'Assessment de DR',
    priority: 'média',
    sources: [{ type: 'manual', confidence: 0.6 }],
    status: 'detected',
    evidence: ['sem plano de DR documentado'],
    justification: 'Prospect sem estratégia de disaster recovery formalizada.',
    confidenceScore: 0.6,
    currentProducts: ['VMware VVF'],
    recommendedProducts: [],
    recommendedServices: ['Assessment de DR'],
  },
  {
    id: 'opp-3',
    companyName: 'Cedro Corp',
    isCustomer: true,
    opportunityScore: 0.41,
    financialPotential: null,
    type: 'optimization',
    product: null,
    service: 'FinOps',
    priority: 'baixa',
    sources: [{ type: 'website', confidence: 0.5 }],
    status: 'reviewed',
    evidence: ['gasto cloud acima da média do segmento'],
    justification: 'Sinal de possível excesso de gasto em cloud, sem dado financeiro confirmado.',
    confidenceScore: 0.4,
    currentProducts: ['AWS'],
    recommendedProducts: [],
    recommendedServices: ['FinOps'],
  },
]
